# Generated by Django 4.2.6 on 2023-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("sales", "Sales"), ("tech", "Tech")], max_length=10
                    ),
                ),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(max_length=200)),
                ("option_4", models.CharField(max_length=200)),
                ("option_1_ps", models.IntegerField()),
                ("option_2_ps", models.IntegerField()),
                ("option_3_ps", models.IntegerField()),
                ("option_4_ps", models.IntegerField()),
            ],
        ),
    ]
