# Generated by Django 4.2.6 on 2023-10-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("tech_score", models.PositiveIntegerField(default=0)),
                ("sales_score", models.PositiveIntegerField(default=0)),
                (
                    "dominant_domain",
                    models.CharField(
                        blank=True,
                        choices=[("tech", "Tech"), ("sales", "Sales")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
                ("leetcode_link", models.URLField(blank=True, null=True)),
                ("hacker_rank_link", models.URLField(blank=True, null=True)),
                ("skill_analysis_score", models.PositiveIntegerField(default=0)),
                ("social_media_matching_score", models.PositiveIntegerField(default=0)),
                ("proof_of_work_score", models.PositiveIntegerField(default=0)),
                ("project_analysis_score", models.PositiveIntegerField(default=0)),
                ("primary_verification_score", models.PositiveIntegerField(default=0)),
                ("salary_data_score", models.PositiveIntegerField(default=0)),
                (
                    "domain_suitability",
                    models.CharField(
                        blank=True,
                        choices=[("sales", "Sales"), ("tech", "Tech")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.PositiveIntegerField()),
                ("points_awarded", models.PositiveIntegerField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions_app.applicant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions_app.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resumes/")),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions_app.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions_app.applicant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions_app.question",
                    ),
                ),
            ],
        ),
    ]
