# Generated by Django 4.2.6 on 2023-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions_app", "0003_remove_applicant_proof_of_work_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="IQQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("IQ_sales", "iq_Sales"), ("IQ_tech", "iq_Tech")],
                        max_length=10,
                    ),
                ),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(max_length=200)),
                ("option_4", models.CharField(max_length=200)),
                ("correct_answer", models.CharField(max_length=200)),
            ],
        ),
    ]
